name: Sync upstream & Build (daily, fixed filename)

on:
  workflow_dispatch:
  schedule:
    # 每天 09:00 UTC 运行（洛杉矶大致凌晨）
    - cron: "0 9 * * *"

permissions:
  contents: write  # 需要写权限才能 push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          # TODO: 替换为真实上游仓库
          git remote add upstream https://github.com/BKN46/WarSoul-Tools.git || true
          git fetch upstream

      - name: Merge upstream/main -> main (fast-forward if possible)
        run: |
          git checkout main
          git merge --ff-only upstream/main || (git rebase upstream/main || true)

      - name: Push updated main (if any)
        run: |
          git fetch origin main
          # 只在本地有新提交时才 push
          if git rev-list origin/main..HEAD | grep -q .; then
            git push origin HEAD:main
          else
            echo "No upstream changes to push."
          fi

  build-and-commit:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (updated main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 为了能够提交回仓库

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: npm run build

      - name: Set build file path (fixed filename)
        id: ver
        run: echo "filepath=build/WSTools.js" >> $GITHUB_OUTPUT

      - name: Ensure build output exists
        run: |
          ls -lah build || true
          test -f "${{ steps.ver.outputs.filepath }}" || (echo "Not found: ${{ steps.ver.outputs.filepath }}" && exit 1)

      - name: Commit build output to /build
        run: |
          # 如果 .gitignore 忽略了 build/，用 -f 强制加入
          git add -f "${{ steps.ver.outputs.filepath }}" || true

          if git diff --cached --quiet; then
            echo "No changes in build output."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "chore(build): update WSTools.js [skip ci]"
          git push origin HEAD:main
