name: Sync upstream & Build (daily, normalize filename)

on:
  workflow_dispatch:
  schedule:
    # 每天 09:00 UTC 运行（洛杉矶大致凌晨）
    - cron: "0 9 * * *"

permissions:
  contents: write  # 允许推送到仓库

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          # TODO: 替换为你的上游仓库地址
          git remote add upstream https://github.com/BKN46/WarSoul-Tools.git || true
          git fetch upstream

      - name: Merge upstream/main -> main (fast-forward if possible)
        run: |
          git checkout main
          git merge --ff-only upstream/main || (git rebase upstream/main || true)

      - name: Push updated main (if any)
        run: |
          git fetch origin main
          if git rev-list origin/main..HEAD | grep -q .; then
            git push origin HEAD:main
          else
            echo "No upstream changes to push."
          fi

  build-and-commit:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (updated main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要完整历史以便提交

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: npm run build

      # 关键：把带版本号的构建产物复制为固定文件名
      - name: Normalize filename to build/WSTools.js
        run: |
          set -e
          FILE=$(ls -1 build/WSTools-*.js 2>/dev/null | head -n1 || true)
          if [ -z "$FILE" ]; then
            echo "No file matched build/WSTools-*.js"
            echo "Existing files in build/:"
            ls -lah build || true
            exit 1
          fi
          echo "Found: $FILE"
          cp "$FILE" build/WSTools.js

      - name: Ensure build output exists
        run: |
          ls -lah build || true
          test -f "build/WSTools.js" || (echo "Not found: build/WSTools.js" && exit 1)

      - name: Commit build/WSTools.js
        run: |
          # 如 .gitignore 忽略了 build/，强制加入
          git add -f build/WSTools.js || true

          if git diff --cached --quiet; then
            echo "No changes in build output."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "chore(build): update WSTools.js [skip ci]"
          git push origin HEAD:main
